export const tokenSections = [
  {
    key: "tokenLaunchpad",
    title: "token launchpad",
    icon: "/rocket.webp",
    items: ["create presale", "launches list", "create token"],
  },
  { title: "token creator", icon: "/tokenCreator.webp" },
  {
    key: "airdropToken",
    title: "airdrop token",
    icon: "/kite.svg",
    items: ["multisender", "create claim site"],
  },
  { title: "create liquidity pool", icon: "/graphd.webp" },
  { title: "volumn bot", icon: "/people.webp" },
  { title: "AllinOne Pro Bundler", icon: "/allione.svg", external: true },
  {
    key: "pumpFunZone",
    title: "Pump.fun Zone",
    icon: "/pump.svg",
    items: [
      "pump bundler",
      "pump volume bot",
      "pump comments bot",
      "pump micro trading",
      "pump bundle buy",
      "pump bundle sell",
      "anti-MEV volume bot",
      "pump buy holders",
    ],
  },
  {
    key: "pumpSwapZone",
    title: "Pump Swap Zone",
    icon: "/swap.svg",
    items: [
      "pump swap volume bot",
      "pump swap bundle buy",
      "pump swap bundle sell",
      "pump swap anti mev",
    ],
  },
  {
    key: "moonitZone",
    title: "moonit zone",
    icon: "/moonit.png",
    items: ["moonit bundler", "moonit volume bot", "moonit bundle buy", "moonit bundle sell"],
  },
  {
    key: "launchLabZone",
    title: "LaunchLab Zone",
    icon: "/lab.svg",
    items: ["launchLab bundler", "launchLab volume bot", "launchLab bundle buy", "launchLab bundle sell"],
  },
  {
    key: "bonkZone",
    title: "bonk zone",
    icon: "/bonk.png",
    items: ["bonk bundler", "bonk volume bot", "bonk bundle buy", "bonk bundle sell"],
  },
  {
    key: "bagZone",
    title: "bag zone",
    icon: "/bag.webp",
    items: ["bags bundler", "bags volume bot", "bags bundle buy", "bags bundle sell"],
  },
  {
    key: "jupiterStudioZone",
    title: "jupiter studio zone",
    icon: "/jupiter.svg",
    items: ["jupiter studio volume bot", "jupiter studio bundle buy", "jupiter studio bundle sell"],
  },
  { title: "token vesting", icon: "/lock.webp" },
  { title: "create token staking", icon: "/hammer.webp" },
  {
    key: "revokeAuthorities",
    title: "revoke authorities",
    icon: "/span.webp",
    items: ["revoke freeze authority", "revoke mint authority", "revoke update authority"],
  },
  {
    key: "manageLiquidity",
    title: "manage liquidity",
    icon: "/manage.webp",
    items: ["liquidity remover", "liquidity adder", "create openbook market", "create liquidity pool"],
  },
  {
    key: "tokenManager",
    title: "token manager",
    icon: "/setting.webp",
    items: [
      "create openbook market",
      "create tax token",
      "update token metadata",
      "token mint",
      "hashlist NFT",
      "revoke freeze authority",
      "freeze token account",
      "unfreeze token account",
      "solana wrapper",
    ],
  },
  {
    key: "snapshotHolders",
    title: "snapshot holders",
    icon: "/snap.webp",
    items: ["snapshot token holders", "snap NFT holders"],
  },
  { title: "token incinerator", icon: "/fire.webp" },
  { title: "mixoor.fun", icon: "/mixoor.png" },
];

export const blockchainOptions = [
  ["solana", "/solana.webp", "solana"],
  ["etherum", "/etherum.webp", "etherum"],
  ["base", "/base.webp", "base"],
  ["polygon", "/polygon.webp", "polygon"],
  ["arbitrum", "/arbitrum.webp", "arbitrum"],
  ["avalanche", "/avalanche.webp", "avalanche"],
  ["binance", "/binance.webp", "binance"],
  ["blast", "/blast.webp", "blast"],
  ["hydra", "/hydra.png", "hydra"],
  ["sui", "/sui.webp", "SUI"],
  ["eclipse", "/eclipise.webp", "eclipse"],
];
